name: ehliyetim
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: lib/assets/fonts/ReadexPro/ReadexPro-Medium.ttf
        - asset: lib/assets/fonts/ReadexPro/ReadexPro-ExtraLight.ttf
          weight: 100 
        - asset: lib/assets/fonts/ReadexPro/ReadexPro-Light.ttf
          weight: 300 
        - asset: lib/assets/fonts/ReadexPro/ReadexPro-Regular.ttf
          weight: 500 
        - asset: lib/assets/fonts/ReadexPro/ReadexPro-SemiBold.ttf
          weight: 700 
        - asset: lib/assets/fonts/ReadexPro/ReadexPro-Bold.ttf
          weight: 800 